#  Configuration For Development Profile
# App Configuration
app:
  port: 8080
  base-url: "http://localhost:${app.port}"
  encryption:
    secret: ${TWO_FA_SECRET_KEY}

# Security Configuration
security:
  bcrypt:
    strength: 10

# Server Configuration
server:
  port: ${app.port}
  servlet:
    session:
      timeout: 604800
      cookie:
        name: XSESSIONID
        domain: localhost
        path: /
        max-age: 604800 # 7 days
        secure: false
        http-only: true
        same-site: strict
      tracking-modes: cookie

# Application Configuration
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Zovo

  # Database Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
      minimum-idle: 5
      maximum-pool-size: 20

  # JPA Configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        connection:
          url: ${spring.datasource.url}
          driver_class: ${spring.datasource.driver-class-name}
          username: ${spring.datasource.username}
          password: ${spring.datasource.password}
          autocommit: ${spring.datasource.hikari.auto-commit}
          isolation: ${spring.datasource.hikari.transaction-isolation}
          pool_size: ${spring.datasource.hikari.maximum-pool-size}

  # Database Migration Configuration
  flyway:
    locations: classpath:db/migrations
    enabled: true
    baseline-on-migrate: true

  # Output Configuration
  output:
    ansi:
      enabled: ALWAYS


  # SMTP Settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    display-name: ${SMTP_DISPLAY_NAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
      password: yourStrongPassword
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  session:
    redis:
      namespace: spring:session  # Optional prefix for session keys
      flush-mode: on-save        # Optional, when to flush to Redis

  cache:
    type: redis


  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile


# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
