#  Configuration For Development Profile

# Security Configuration
security:
  bcrypt:
    strength: 12

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

# Server Configuration
server:
  port: 8080
  servlet:
    session:
      timeout: 7d
      cookie:
        name: BLABLAID
        domain: localhost
        path: /
        max-age: 604800 # 7 days
        secure: false
        http-only: true
        same-site: strict


# Application Configuration
spring:
  application:
    name: Zovo

  # Database Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  # JPA Configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Database Migration Configuration
  flyway:
    locations: classpath:db/migrations
    enabled: true

  # Output Configuration
  output:
    ansi:
      enabled: ALWAYS

  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile